apiVersion: apps/v1
kind: Deployment
metadata:
  name: savevid-processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: savevid-processor-pod
  template:
    metadata:
      labels:
        app: savevid-processor-pod
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: "workload-identity-sa"
      containers:
      - name: savevid-processor-container
        resources:
          limits:
            memory: "1024M"
            cpu: "0.6"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "token-provider-class"
